//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/internal/bind/DateTypeAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DateTypeAdapter")
#ifdef RESTRICT_DateTypeAdapter
#define INCLUDE_ALL_DateTypeAdapter 0
#else
#define INCLUDE_ALL_DateTypeAdapter 1
#endif
#undef RESTRICT_DateTypeAdapter

#if !defined (ComGoogleGsonInternalBindDateTypeAdapter_) && (INCLUDE_ALL_DateTypeAdapter || defined(INCLUDE_ComGoogleGsonInternalBindDateTypeAdapter))
#define ComGoogleGsonInternalBindDateTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class JavaUtilDate;
@protocol ComGoogleGsonTypeAdapterFactory;

@interface ComGoogleGsonInternalBindDateTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)init;

- (JavaUtilDate *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (JavaUtilDate *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (JavaUtilDate *)fromJsonWithNSString:(NSString *)arg0;

- (JavaUtilDate *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(JavaUtilDate *)value;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonInternalBindDateTypeAdapter)

inline id<ComGoogleGsonTypeAdapterFactory> ComGoogleGsonInternalBindDateTypeAdapter_get_FACTORY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<ComGoogleGsonTypeAdapterFactory> ComGoogleGsonInternalBindDateTypeAdapter_FACTORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonInternalBindDateTypeAdapter, FACTORY, id<ComGoogleGsonTypeAdapterFactory>)

FOUNDATION_EXPORT void ComGoogleGsonInternalBindDateTypeAdapter_init(ComGoogleGsonInternalBindDateTypeAdapter *self);

FOUNDATION_EXPORT ComGoogleGsonInternalBindDateTypeAdapter *new_ComGoogleGsonInternalBindDateTypeAdapter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonInternalBindDateTypeAdapter *create_ComGoogleGsonInternalBindDateTypeAdapter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindDateTypeAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_DateTypeAdapter")
