//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/ExclusionStrategy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ExclusionStrategy")
#ifdef RESTRICT_ExclusionStrategy
#define INCLUDE_ALL_ExclusionStrategy 0
#else
#define INCLUDE_ALL_ExclusionStrategy 1
#endif
#undef RESTRICT_ExclusionStrategy

#if !defined (ComGoogleGsonExclusionStrategy_) && (INCLUDE_ALL_ExclusionStrategy || defined(INCLUDE_ComGoogleGsonExclusionStrategy))
#define ComGoogleGsonExclusionStrategy_

@class ComGoogleGsonFieldAttributes;
@class IOSClass;

@protocol ComGoogleGsonExclusionStrategy < JavaObject >

- (jboolean)shouldSkipFieldWithComGoogleGsonFieldAttributes:(ComGoogleGsonFieldAttributes *)f;

- (jboolean)shouldSkipClassWithIOSClass:(IOSClass *)clazz;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonExclusionStrategy)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonExclusionStrategy)

#endif

#pragma pop_macro("INCLUDE_ALL_ExclusionStrategy")
