//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/annotations/Expose.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Expose")
#ifdef RESTRICT_Expose
#define INCLUDE_ALL_Expose 0
#else
#define INCLUDE_ALL_Expose 1
#endif
#undef RESTRICT_Expose

#if !defined (ComGoogleGsonAnnotationsExpose_) && (INCLUDE_ALL_Expose || defined(INCLUDE_ComGoogleGsonAnnotationsExpose))
#define ComGoogleGsonAnnotationsExpose_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol ComGoogleGsonAnnotationsExpose < JavaLangAnnotationAnnotation >

@property (readonly) jboolean serialize;
@property (readonly) jboolean deserialize;

@end

@interface ComGoogleGsonAnnotationsExpose : NSObject < ComGoogleGsonAnnotationsExpose > {
 @public
  jboolean serialize_;
  jboolean deserialize_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsExpose)

FOUNDATION_EXPORT id<ComGoogleGsonAnnotationsExpose> create_ComGoogleGsonAnnotationsExpose(jboolean deserialize, jboolean serialize);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsExpose)

#endif

#pragma pop_macro("INCLUDE_ALL_Expose")
