//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/FieldNamingStrategy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_FieldNamingStrategy")
#ifdef RESTRICT_FieldNamingStrategy
#define INCLUDE_ALL_FieldNamingStrategy 0
#else
#define INCLUDE_ALL_FieldNamingStrategy 1
#endif
#undef RESTRICT_FieldNamingStrategy

#if !defined (ComGoogleGsonFieldNamingStrategy_) && (INCLUDE_ALL_FieldNamingStrategy || defined(INCLUDE_ComGoogleGsonFieldNamingStrategy))
#define ComGoogleGsonFieldNamingStrategy_

@class JavaLangReflectField;

@protocol ComGoogleGsonFieldNamingStrategy < JavaObject >

- (NSString *)translateNameWithJavaLangReflectField:(JavaLangReflectField *)f;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFieldNamingStrategy)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFieldNamingStrategy)

#endif

#pragma pop_macro("INCLUDE_ALL_FieldNamingStrategy")
