//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/InstanceCreator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_InstanceCreator")
#ifdef RESTRICT_InstanceCreator
#define INCLUDE_ALL_InstanceCreator 0
#else
#define INCLUDE_ALL_InstanceCreator 1
#endif
#undef RESTRICT_InstanceCreator

#if !defined (ComGoogleGsonInstanceCreator_) && (INCLUDE_ALL_InstanceCreator || defined(INCLUDE_ComGoogleGsonInstanceCreator))
#define ComGoogleGsonInstanceCreator_

@protocol JavaLangReflectType;

@protocol ComGoogleGsonInstanceCreator < JavaObject >

- (id)createInstanceWithJavaLangReflectType:(id<JavaLangReflectType>)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInstanceCreator)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInstanceCreator)

#endif

#pragma pop_macro("INCLUDE_ALL_InstanceCreator")
