//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/JsonDeserializer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonDeserializer")
#ifdef RESTRICT_JsonDeserializer
#define INCLUDE_ALL_JsonDeserializer 0
#else
#define INCLUDE_ALL_JsonDeserializer 1
#endif
#undef RESTRICT_JsonDeserializer

#if !defined (ComGoogleGsonJsonDeserializer_) && (INCLUDE_ALL_JsonDeserializer || defined(INCLUDE_ComGoogleGsonJsonDeserializer))
#define ComGoogleGsonJsonDeserializer_

@class ComGoogleGsonJsonElement;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol JavaLangReflectType;

@protocol ComGoogleGsonJsonDeserializer < JavaObject >

- (id)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
  withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonDeserializer)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonDeserializer)

#endif

#pragma pop_macro("INCLUDE_ALL_JsonDeserializer")
