//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/internal/bind/JsonAdapterAnnotationTypeAdapterFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory")
#ifdef RESTRICT_JsonAdapterAnnotationTypeAdapterFactory
#define INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory 0
#else
#define INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory 1
#endif
#undef RESTRICT_JsonAdapterAnnotationTypeAdapterFactory

#if !defined (ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_) && (INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory || defined(INCLUDE_ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory))
#define ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_

#define RESTRICT_TypeAdapterFactory 1
#define INCLUDE_ComGoogleGsonTypeAdapterFactory 1
#include "TypeAdapterFactory.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonInternalConstructorConstructor;
@class ComGoogleGsonReflectTypeToken;
@class ComGoogleGsonTypeAdapter;
@protocol ComGoogleGsonAnnotationsJsonAdapter;

@interface ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory : NSObject < ComGoogleGsonTypeAdapterFactory >

#pragma mark Public

- (instancetype)initWithComGoogleGsonInternalConstructorConstructor:(ComGoogleGsonInternalConstructorConstructor *)constructorConstructor;

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)targetType;

#pragma mark Package-Private

- (ComGoogleGsonTypeAdapter *)getTypeAdapterWithComGoogleGsonInternalConstructorConstructor:(ComGoogleGsonInternalConstructorConstructor *)constructorConstructor
                                                                      withComGoogleGsonGson:(ComGoogleGsonGson *)gson
                                                          withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type
                                                    withComGoogleGsonAnnotationsJsonAdapter:(id<ComGoogleGsonAnnotationsJsonAdapter>)annotation;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory)

FOUNDATION_EXPORT void ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory *self, ComGoogleGsonInternalConstructorConstructor *constructorConstructor);

FOUNDATION_EXPORT ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory *new_ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(ComGoogleGsonInternalConstructorConstructor *constructorConstructor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory *create_ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(ComGoogleGsonInternalConstructorConstructor *constructorConstructor);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory)

#endif

#pragma pop_macro("INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory")
