//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/JsonDeserializationContext.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonDeserializationContext")
#ifdef RESTRICT_JsonDeserializationContext
#define INCLUDE_ALL_JsonDeserializationContext 0
#else
#define INCLUDE_ALL_JsonDeserializationContext 1
#endif
#undef RESTRICT_JsonDeserializationContext

#if !defined (ComGoogleGsonJsonDeserializationContext_) && (INCLUDE_ALL_JsonDeserializationContext || defined(INCLUDE_ComGoogleGsonJsonDeserializationContext))
#define ComGoogleGsonJsonDeserializationContext_

@class ComGoogleGsonJsonElement;
@protocol JavaLangReflectType;

@protocol ComGoogleGsonJsonDeserializationContext < JavaObject >

- (id)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonDeserializationContext)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonDeserializationContext)

#endif

#pragma pop_macro("INCLUDE_ALL_JsonDeserializationContext")
