//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/internal/LazilyParsedNumber.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LazilyParsedNumber")
#ifdef RESTRICT_LazilyParsedNumber
#define INCLUDE_ALL_LazilyParsedNumber 0
#else
#define INCLUDE_ALL_LazilyParsedNumber 1
#endif
#undef RESTRICT_LazilyParsedNumber

#if !defined (ComGoogleGsonInternalLazilyParsedNumber_) && (INCLUDE_ALL_LazilyParsedNumber || defined(INCLUDE_ComGoogleGsonInternalLazilyParsedNumber))
#define ComGoogleGsonInternalLazilyParsedNumber_

@interface ComGoogleGsonInternalLazilyParsedNumber : NSNumber

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)value;

- (jdouble)doubleValue;

- (jboolean)isEqual:(id)obj;

- (jfloat)floatValue;

- (NSUInteger)hash;

- (jint)intValue;

- (jlong)longLongValue;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLazilyParsedNumber)

FOUNDATION_EXPORT void ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(ComGoogleGsonInternalLazilyParsedNumber *self, NSString *value);

FOUNDATION_EXPORT ComGoogleGsonInternalLazilyParsedNumber *new_ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonInternalLazilyParsedNumber *create_ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLazilyParsedNumber)

#endif

#pragma pop_macro("INCLUDE_ALL_LazilyParsedNumber")
