//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/internal/ObjectConstructor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObjectConstructor")
#ifdef RESTRICT_ObjectConstructor
#define INCLUDE_ALL_ObjectConstructor 0
#else
#define INCLUDE_ALL_ObjectConstructor 1
#endif
#undef RESTRICT_ObjectConstructor

#if !defined (ComGoogleGsonInternalObjectConstructor_) && (INCLUDE_ALL_ObjectConstructor || defined(INCLUDE_ComGoogleGsonInternalObjectConstructor))
#define ComGoogleGsonInternalObjectConstructor_

@protocol ComGoogleGsonInternalObjectConstructor < JavaObject >

- (id)construct;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalObjectConstructor)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalObjectConstructor)

#endif

#pragma pop_macro("INCLUDE_ALL_ObjectConstructor")
