//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/annotations/Since.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Since")
#ifdef RESTRICT_Since
#define INCLUDE_ALL_Since 0
#else
#define INCLUDE_ALL_Since 1
#endif
#undef RESTRICT_Since

#if !defined (ComGoogleGsonAnnotationsSince_) && (INCLUDE_ALL_Since || defined(INCLUDE_ComGoogleGsonAnnotationsSince))
#define ComGoogleGsonAnnotationsSince_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol ComGoogleGsonAnnotationsSince < JavaLangAnnotationAnnotation >

@property (readonly) jdouble value;

@end

@interface ComGoogleGsonAnnotationsSince : NSObject < ComGoogleGsonAnnotationsSince > {
 @public
  jdouble value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsSince)

FOUNDATION_EXPORT id<ComGoogleGsonAnnotationsSince> create_ComGoogleGsonAnnotationsSince(jdouble value);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsSince)

#endif

#pragma pop_macro("INCLUDE_ALL_Since")
