//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/internal/bind/SqlDateTypeAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SqlDateTypeAdapter")
#ifdef RESTRICT_SqlDateTypeAdapter
#define INCLUDE_ALL_SqlDateTypeAdapter 0
#else
#define INCLUDE_ALL_SqlDateTypeAdapter 1
#endif
#undef RESTRICT_SqlDateTypeAdapter

#if !defined (ComGoogleGsonInternalBindSqlDateTypeAdapter_) && (INCLUDE_ALL_SqlDateTypeAdapter || defined(INCLUDE_ComGoogleGsonInternalBindSqlDateTypeAdapter))
#define ComGoogleGsonInternalBindSqlDateTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class JavaSqlDate;
@protocol ComGoogleGsonTypeAdapterFactory;

@interface ComGoogleGsonInternalBindSqlDateTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)init;

- (JavaSqlDate *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (JavaSqlDate *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (JavaSqlDate *)fromJsonWithNSString:(NSString *)arg0;

- (JavaSqlDate *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(JavaSqlDate *)value;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonInternalBindSqlDateTypeAdapter)

inline id<ComGoogleGsonTypeAdapterFactory> ComGoogleGsonInternalBindSqlDateTypeAdapter_get_FACTORY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<ComGoogleGsonTypeAdapterFactory> ComGoogleGsonInternalBindSqlDateTypeAdapter_FACTORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonInternalBindSqlDateTypeAdapter, FACTORY, id<ComGoogleGsonTypeAdapterFactory>)

FOUNDATION_EXPORT void ComGoogleGsonInternalBindSqlDateTypeAdapter_init(ComGoogleGsonInternalBindSqlDateTypeAdapter *self);

FOUNDATION_EXPORT ComGoogleGsonInternalBindSqlDateTypeAdapter *new_ComGoogleGsonInternalBindSqlDateTypeAdapter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonInternalBindSqlDateTypeAdapter *create_ComGoogleGsonInternalBindSqlDateTypeAdapter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindSqlDateTypeAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_SqlDateTypeAdapter")
