//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/internal/Streams.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Streams")
#ifdef RESTRICT_Streams
#define INCLUDE_ALL_Streams 0
#else
#define INCLUDE_ALL_Streams 1
#endif
#undef RESTRICT_Streams

#if !defined (ComGoogleGsonInternalStreams_) && (INCLUDE_ALL_Streams || defined(INCLUDE_ComGoogleGsonInternalStreams))
#define ComGoogleGsonInternalStreams_

@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoWriter;
@protocol JavaLangAppendable;

@interface ComGoogleGsonInternalStreams : NSObject

#pragma mark Public

+ (ComGoogleGsonJsonElement *)parseWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader;

+ (void)writeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)element
        withComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)writer;

+ (JavaIoWriter *)writerForAppendableWithJavaLangAppendable:(id<JavaLangAppendable>)appendable;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalStreams)

FOUNDATION_EXPORT ComGoogleGsonJsonElement *ComGoogleGsonInternalStreams_parseWithComGoogleGsonStreamJsonReader_(ComGoogleGsonStreamJsonReader *reader);

FOUNDATION_EXPORT void ComGoogleGsonInternalStreams_writeWithComGoogleGsonJsonElement_withComGoogleGsonStreamJsonWriter_(ComGoogleGsonJsonElement *element, ComGoogleGsonStreamJsonWriter *writer);

FOUNDATION_EXPORT JavaIoWriter *ComGoogleGsonInternalStreams_writerForAppendableWithJavaLangAppendable_(id<JavaLangAppendable> appendable);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalStreams)

#endif

#pragma pop_macro("INCLUDE_ALL_Streams")
