//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/TypeAdapterFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TypeAdapterFactory")
#ifdef RESTRICT_TypeAdapterFactory
#define INCLUDE_ALL_TypeAdapterFactory 0
#else
#define INCLUDE_ALL_TypeAdapterFactory 1
#endif
#undef RESTRICT_TypeAdapterFactory

#if !defined (ComGoogleGsonTypeAdapterFactory_) && (INCLUDE_ALL_TypeAdapterFactory || defined(INCLUDE_ComGoogleGsonTypeAdapterFactory))
#define ComGoogleGsonTypeAdapterFactory_

@class ComGoogleGsonGson;
@class ComGoogleGsonReflectTypeToken;
@class ComGoogleGsonTypeAdapter;

@protocol ComGoogleGsonTypeAdapterFactory < JavaObject >

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonTypeAdapterFactory)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonTypeAdapterFactory)

#endif

#pragma pop_macro("INCLUDE_ALL_TypeAdapterFactory")
