//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/internal/bind/TypeAdapterRuntimeTypeWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TypeAdapterRuntimeTypeWrapper")
#ifdef RESTRICT_TypeAdapterRuntimeTypeWrapper
#define INCLUDE_ALL_TypeAdapterRuntimeTypeWrapper 0
#else
#define INCLUDE_ALL_TypeAdapterRuntimeTypeWrapper 1
#endif
#undef RESTRICT_TypeAdapterRuntimeTypeWrapper

#if !defined (ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper_) && (INCLUDE_ALL_TypeAdapterRuntimeTypeWrapper || defined(INCLUDE_ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper))
#define ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@protocol JavaLangReflectType;

@interface ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper : ComGoogleGsonTypeAdapter

#pragma mark Public

- (id)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(id)value;

#pragma mark Package-Private

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)context
             withComGoogleGsonTypeAdapter:(ComGoogleGsonTypeAdapter *)delegate
                  withJavaLangReflectType:(id<JavaLangReflectType>)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper)

FOUNDATION_EXPORT void ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper_initWithComGoogleGsonGson_withComGoogleGsonTypeAdapter_withJavaLangReflectType_(ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper *self, ComGoogleGsonGson *context, ComGoogleGsonTypeAdapter *delegate, id<JavaLangReflectType> type);

FOUNDATION_EXPORT ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper *new_ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper_initWithComGoogleGsonGson_withComGoogleGsonTypeAdapter_withJavaLangReflectType_(ComGoogleGsonGson *context, ComGoogleGsonTypeAdapter *delegate, id<JavaLangReflectType> type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper *create_ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper_initWithComGoogleGsonGson_withComGoogleGsonTypeAdapter_withJavaLangReflectType_(ComGoogleGsonGson *context, ComGoogleGsonTypeAdapter *delegate, id<JavaLangReflectType> type);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_TypeAdapterRuntimeTypeWrapper")
