//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson/build/mainTranslationExtraction/com/google/gson/annotations/Until.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Until")
#ifdef RESTRICT_Until
#define INCLUDE_ALL_Until 0
#else
#define INCLUDE_ALL_Until 1
#endif
#undef RESTRICT_Until

#if !defined (ComGoogleGsonAnnotationsUntil_) && (INCLUDE_ALL_Until || defined(INCLUDE_ComGoogleGsonAnnotationsUntil))
#define ComGoogleGsonAnnotationsUntil_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol ComGoogleGsonAnnotationsUntil < JavaLangAnnotationAnnotation >

@property (readonly) jdouble value;

@end

@interface ComGoogleGsonAnnotationsUntil : NSObject < ComGoogleGsonAnnotationsUntil > {
 @public
  jdouble value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsUntil)

FOUNDATION_EXPORT id<ComGoogleGsonAnnotationsUntil> create_ComGoogleGsonAnnotationsUntil(jdouble value);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsUntil)

#endif

#pragma pop_macro("INCLUDE_ALL_Until")
